package dev.wasabules.dukto.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog

/**
 * Compact dialog driving the v2 PSK pairing flow. The dialog has three
 * states:
 *  - menu:     pick "generate" or "enter"
 *  - generate: show the 5-word passphrase the user reads out loud
 *  - enter:    text input the user types the code into
 *
 * On a successful "enter" submission, [onPaired] fires and the dialog
 * dismisses itself. Cancel from any state calls [onCancel] which also
 * clears any armed PSK on the engine.
 */
@Composable
fun PairingDialog(
    peerLabel: String,
    onGenerate: () -> String,
    onSubmitCode: (String) -> Result<Unit>,
    onCancel: () -> Unit,
) {
    var mode by remember { mutableStateOf("menu") }
    var generated by remember { mutableStateOf("") }
    var code by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }

    Dialog(onDismissRequest = onCancel) {
        Column(
            modifier = Modifier
                .clip(RoundedCornerShape(16.dp))
                .background(MaterialTheme.colorScheme.surface)
                .padding(20.dp)
                .fillMaxWidth(),
        ) {
            Text("Pair with $peerLabel", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(8.dp))
            when (mode) {
                "menu" -> {
                    Text(
                        "Both peers must enter the same 5-word code. Either generate one and read it out, or type the code the other peer just generated.",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(12.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(onClick = {
                            generated = onGenerate()
                            mode = "generate"
                        }) { Text("Generate") }
                        OutlinedButton(onClick = { mode = "enter" }) { Text("Enter code") }
                    }
                }
                "generate" -> {
                    Text(
                        "Read this code to the other peer (valid 60 s):",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(6.dp))
                    Text(
                        generated,
                        style = MaterialTheme.typography.titleLarge.copy(
                            fontWeight = FontWeight.SemiBold,
                            fontFamily = FontFamily.Monospace,
                        ),
                    )
                    Spacer(Modifier.height(6.dp))
                    Text(
                        "Once their handshake lands the peer's lock badge flips to 🔒.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                "enter" -> {
                    Text(
                        "Type the 5-word code the other peer generated:",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(6.dp))
                    OutlinedTextField(
                        value = code,
                        onValueChange = { code = it; error = null },
                        modifier = Modifier.fillMaxWidth(),
                        placeholder = { Text("apple-tiger-river-ocean-music") },
                        singleLine = true,
                    )
                    error?.let {
                        Spacer(Modifier.height(6.dp))
                        Text(it, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)
                    }
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(
                            onClick = {
                                val r = onSubmitCode(code)
                                r.exceptionOrNull()?.let { error = it.message ?: it.javaClass.simpleName }
                                if (r.isSuccess) onCancel()
                            },
                            enabled = code.isNotBlank(),
                        ) { Text("Pair") }
                    }
                }
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Spacer(Modifier.fillMaxWidth().height(0.dp))
            }
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.End,
            ) {
                TextButton(onClick = onCancel) { Text("Close") }
            }
        }
    }
}
