package dev.wasabules.dukto.ui

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.Image
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedButton
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.ui.graphics.asImageBitmap
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.window.Dialog
import androidx.core.content.ContextCompat
import com.journeyapps.barcodescanner.ScanContract
import com.journeyapps.barcodescanner.ScanOptions
import kotlinx.coroutines.launch

/**
 * Compact dialog driving the v2 PSK pairing flow. The dialog has three
 * states:
 *  - menu:     pick "generate" or "enter"
 *  - generate: show the 5-word passphrase the user reads out loud
 *  - enter:    text input the user types the code into
 *
 * On a successful "enter" submission, [onPaired] fires and the dialog
 * dismisses itself. Cancel from any state calls [onCancel] which also
 * clears any armed PSK on the engine.
 */
@Composable
fun PairingDialog(
    peerLabel: String,
    onGenerate: () -> String,
    /** Called on a background thread (Dispatchers.IO) — Socket I/O is
     *  forbidden on the main thread, so the caller's lambda runs the
     *  Noise XXpsk2 handshake off the UI dispatcher. */
    onSubmitCode: suspend (String) -> Result<Unit>,
    onCancel: () -> Unit,
) {
    var mode by remember { mutableStateOf("menu") }
    var generated by remember { mutableStateOf("") }
    var code by remember { mutableStateOf("") }
    var error by remember { mutableStateOf<String?>(null) }
    var busy by remember { mutableStateOf(false) }
    var pendingScan by remember { mutableStateOf(false) }
    val scope = rememberCoroutineScope()
    val context = LocalContext.current

    // ZXing scan launcher — fires when the user taps "Scan QR" inside the
    // "enter code" path. Result is the raw passphrase the other peer's
    // dialog encoded in the QR; we drop it straight into the text field
    // so the user can review before submitting.
    val scanner = rememberLauncherForActivityResult(ScanContract()) { result ->
        val content = result?.contents
        if (!content.isNullOrBlank()) {
            code = content.trim()
        }
    }
    val cameraPermission = rememberLauncherForActivityResult(
        ActivityResultContracts.RequestPermission(),
    ) { granted ->
        if (granted && pendingScan) {
            pendingScan = false
            scanner.launch(scanOptions())
        } else {
            pendingScan = false
            error = if (!granted) "Camera permission refused" else null
        }
    }
    fun startScan() {
        if (ContextCompat.checkSelfPermission(
                context, android.Manifest.permission.CAMERA,
            ) == android.content.pm.PackageManager.PERMISSION_GRANTED
        ) {
            scanner.launch(scanOptions())
        } else {
            pendingScan = true
            cameraPermission.launch(android.Manifest.permission.CAMERA)
        }
    }

    Dialog(onDismissRequest = onCancel) {
        Column(
            modifier = Modifier
                .clip(RoundedCornerShape(16.dp))
                .background(MaterialTheme.colorScheme.surface)
                .padding(20.dp)
                .fillMaxWidth(),
        ) {
            Text("Pair with $peerLabel", style = MaterialTheme.typography.titleMedium)
            Spacer(Modifier.height(8.dp))
            when (mode) {
                "menu" -> {
                    Text(
                        "Both peers must enter the same 5-word code. Either generate one and read it out, or type the code the other peer just generated.",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(12.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(onClick = {
                            generated = onGenerate()
                            mode = "generate"
                        }) { Text("Generate") }
                        OutlinedButton(onClick = { mode = "enter" }) { Text("Enter code") }
                    }
                }
                "generate" -> {
                    Text(
                        "Read or scan this code on the other peer (valid 60 s):",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(6.dp))
                    Text(
                        generated,
                        style = MaterialTheme.typography.titleLarge.copy(
                            fontWeight = FontWeight.SemiBold,
                            fontFamily = FontFamily.Monospace,
                        ),
                    )
                    Spacer(Modifier.height(8.dp))
                    val qr = remember(generated) {
                        runCatching { dev.wasabules.dukto.eff.encodeQr(generated, 480) }.getOrNull()
                    }
                    if (qr != null) {
                        Image(
                            bitmap = qr.asImageBitmap(),
                            contentDescription = "Pairing QR code",
                            modifier = Modifier.fillMaxWidth().height(220.dp),
                        )
                    }
                    Spacer(Modifier.height(6.dp))
                    Text(
                        "Once their handshake lands the peer's lock badge flips to 🔒.",
                        style = MaterialTheme.typography.bodySmall,
                        color = MaterialTheme.colorScheme.onSurfaceVariant,
                    )
                }
                "enter" -> {
                    Text(
                        "Type the 5-word code, or scan the QR the other peer is showing.",
                        style = MaterialTheme.typography.bodySmall,
                    )
                    Spacer(Modifier.height(6.dp))
                    OutlinedTextField(
                        value = code,
                        onValueChange = { code = it; error = null },
                        modifier = Modifier.fillMaxWidth(),
                        placeholder = { Text("apple-tiger-river-ocean-music") },
                        singleLine = true,
                    )
                    Spacer(Modifier.height(6.dp))
                    OutlinedButton(onClick = { startScan() }) {
                        Text("Scan QR")
                    }
                    error?.let {
                        Spacer(Modifier.height(6.dp))
                        Text(it, style = MaterialTheme.typography.bodySmall, color = MaterialTheme.colorScheme.error)
                    }
                    Spacer(Modifier.height(8.dp))
                    Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                        Button(
                            onClick = {
                                if (busy) return@Button
                                busy = true
                                error = null
                                scope.launch {
                                    val r = onSubmitCode(code)
                                    busy = false
                                    val ex = r.exceptionOrNull()
                                    if (ex != null) {
                                        error = ex.message ?: ex.javaClass.simpleName
                                    } else {
                                        onCancel()
                                    }
                                }
                            },
                            enabled = !busy && code.isNotBlank(),
                        ) { Text(if (busy) "Pairing…" else "Pair") }
                    }
                }
            }
            Spacer(Modifier.height(16.dp))
            Row(verticalAlignment = Alignment.CenterVertically) {
                Spacer(Modifier.fillMaxWidth().height(0.dp))
            }
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.End,
            ) {
                TextButton(onClick = onCancel) { Text("Close") }
            }
        }
    }
}

/**
 * ZXing scanner options tailored for the Dukto pairing flow:
 *  - QR-code only (no other barcode formats compete on the live feed).
 *  - Beep off — this is a privacy/identity ceremony, not a checkout.
 *  - Locked to portrait via [PortraitCaptureActivity] so the camera
 *    matches the rest of the app (the stock CaptureActivity is
 *    landscape-only).
 *  - Custom prompt makes it obvious what we're scanning.
 */
private fun scanOptions(): ScanOptions = ScanOptions().apply {
    setDesiredBarcodeFormats(ScanOptions.QR_CODE)
    setBeepEnabled(false)
    setOrientationLocked(true)
    setCaptureActivity(PortraitCaptureActivity::class.java)
    setPrompt("Scan the pairing code")
}
