// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuddyName() {
  return window['go']['main']['App']['BuddyName']();
}

export function CloseToTray() {
  return window['go']['main']['App']['CloseToTray']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DestDir() {
  return window['go']['main']['App']['DestDir']();
}

export function LocalAddresses() {
  return window['go']['main']['App']['LocalAddresses']();
}

export function Notifications() {
  return window['go']['main']['App']['Notifications']();
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function PickDestDir() {
  return window['go']['main']['App']['PickDestDir']();
}

export function SendFiles(arg1, arg2) {
  return window['go']['main']['App']['SendFiles'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetBuddyName(arg1) {
  return window['go']['main']['App']['SetBuddyName'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetDestDir(arg1) {
  return window['go']['main']['App']['SetDestDir'](arg1);
}

export function SetNotifications(arg1) {
  return window['go']['main']['App']['SetNotifications'](arg1);
}

export function Signature() {
  return window['go']['main']['App']['Signature']();
}
