// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BuddyName():Promise<string>;

export function CloseToTray():Promise<boolean>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DestDir():Promise<string>;

export function LocalAddresses():Promise<Array<string>>;

export function Notifications():Promise<boolean>;

export function Peers():Promise<Array<main.PeerView>>;

export function PickDestDir():Promise<string>;

export function SendFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function SendText(arg1:string,arg2:string):Promise<void>;

export function SetBuddyName(arg1:string):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetDestDir(arg1:string):Promise<void>;

export function SetNotifications(arg1:boolean):Promise<void>;

export function Signature():Promise<string>;
