// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddManualPeer(arg1) {
  return window['go']['main']['App']['AddManualPeer'](arg1);
}

export function AddWhitelist(arg1) {
  return window['go']['main']['App']['AddWhitelist'](arg1);
}

export function Aliases() {
  return window['go']['main']['App']['Aliases']();
}

export function AllowedInterfaces() {
  return window['go']['main']['App']['AllowedInterfaces']();
}

export function AuditEntries() {
  return window['go']['main']['App']['AuditEntries']();
}

export function AvailableInterfaces() {
  return window['go']['main']['App']['AvailableInterfaces']();
}

export function BlockPeer(arg1) {
  return window['go']['main']['App']['BlockPeer'](arg1);
}

export function BlockedPeers() {
  return window['go']['main']['App']['BlockedPeers']();
}

export function BuddyName() {
  return window['go']['main']['App']['BuddyName']();
}

export function CancelTransfer() {
  return window['go']['main']['App']['CancelTransfer']();
}

export function ClearAudit() {
  return window['go']['main']['App']['ClearAudit']();
}

export function ClearCustomAvatar() {
  return window['go']['main']['App']['ClearCustomAvatar']();
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CloseToTray() {
  return window['go']['main']['App']['CloseToTray']();
}

export function ConfirmUnknownPeers() {
  return window['go']['main']['App']['ConfirmUnknownPeers']();
}

export function CopyToClipboard(arg1) {
  return window['go']['main']['App']['CopyToClipboard'](arg1);
}

export function DestDir() {
  return window['go']['main']['App']['DestDir']();
}

export function ExportHistory(arg1, arg2) {
  return window['go']['main']['App']['ExportHistory'](arg1, arg2);
}

export function FileHash(arg1) {
  return window['go']['main']['App']['FileHash'](arg1);
}

export function Fingerprint() {
  return window['go']['main']['App']['Fingerprint']();
}

export function ForgetApprovedPeers() {
  return window['go']['main']['App']['ForgetApprovedPeers']();
}

export function HasCustomAvatar() {
  return window['go']['main']['App']['HasCustomAvatar']();
}

export function History() {
  return window['go']['main']['App']['History']();
}

export function IdleAutoDisableMinutes() {
  return window['go']['main']['App']['IdleAutoDisableMinutes']();
}

export function LargeFileThresholdMB() {
  return window['go']['main']['App']['LargeFileThresholdMB']();
}

export function LocalAddresses() {
  return window['go']['main']['App']['LocalAddresses']();
}

export function LocalAvatarDataURL() {
  return window['go']['main']['App']['LocalAvatarDataURL']();
}

export function ManualPeers() {
  return window['go']['main']['App']['ManualPeers']();
}

export function MaxFilesPerSession() {
  return window['go']['main']['App']['MaxFilesPerSession']();
}

export function MaxPathDepth() {
  return window['go']['main']['App']['MaxPathDepth']();
}

export function MinFreeDiskPercent() {
  return window['go']['main']['App']['MinFreeDiskPercent']();
}

export function Notifications() {
  return window['go']['main']['App']['Notifications']();
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function Peers() {
  return window['go']['main']['App']['Peers']();
}

export function PickAndSetCustomAvatar() {
  return window['go']['main']['App']['PickAndSetCustomAvatar']();
}

export function PickDestDir() {
  return window['go']['main']['App']['PickDestDir']();
}

export function PickExportPath(arg1) {
  return window['go']['main']['App']['PickExportPath'](arg1);
}

export function PickFilesToSend() {
  return window['go']['main']['App']['PickFilesToSend']();
}

export function PickFolderToSend() {
  return window['go']['main']['App']['PickFolderToSend']();
}

export function QRCodeSignature() {
  return window['go']['main']['App']['QRCodeSignature']();
}

export function ReceivingEnabled() {
  return window['go']['main']['App']['ReceivingEnabled']();
}

export function RejectedExtensions() {
  return window['go']['main']['App']['RejectedExtensions']();
}

export function RemoveManualPeer(arg1) {
  return window['go']['main']['App']['RemoveManualPeer'](arg1);
}

export function RemoveWhitelist(arg1) {
  return window['go']['main']['App']['RemoveWhitelist'](arg1);
}

export function ResolvePendingSession(arg1, arg2) {
  return window['go']['main']['App']['ResolvePendingSession'](arg1, arg2);
}

export function RevealInFolder(arg1) {
  return window['go']['main']['App']['RevealInFolder'](arg1);
}

export function SendClipboard(arg1) {
  return window['go']['main']['App']['SendClipboard'](arg1);
}

export function SendFiles(arg1, arg2) {
  return window['go']['main']['App']['SendFiles'](arg1, arg2);
}

export function SendFilesMulti(arg1, arg2) {
  return window['go']['main']['App']['SendFilesMulti'](arg1, arg2);
}

export function SendText(arg1, arg2) {
  return window['go']['main']['App']['SendText'](arg1, arg2);
}

export function SetAlias(arg1, arg2) {
  return window['go']['main']['App']['SetAlias'](arg1, arg2);
}

export function SetAllowedInterfaces(arg1) {
  return window['go']['main']['App']['SetAllowedInterfaces'](arg1);
}

export function SetBuddyName(arg1) {
  return window['go']['main']['App']['SetBuddyName'](arg1);
}

export function SetCloseToTray(arg1) {
  return window['go']['main']['App']['SetCloseToTray'](arg1);
}

export function SetConfirmUnknownPeers(arg1) {
  return window['go']['main']['App']['SetConfirmUnknownPeers'](arg1);
}

export function SetDestDir(arg1) {
  return window['go']['main']['App']['SetDestDir'](arg1);
}

export function SetIdleAutoDisableMinutes(arg1) {
  return window['go']['main']['App']['SetIdleAutoDisableMinutes'](arg1);
}

export function SetLargeFileThresholdMB(arg1) {
  return window['go']['main']['App']['SetLargeFileThresholdMB'](arg1);
}

export function SetMaxFilesPerSession(arg1) {
  return window['go']['main']['App']['SetMaxFilesPerSession'](arg1);
}

export function SetMaxPathDepth(arg1) {
  return window['go']['main']['App']['SetMaxPathDepth'](arg1);
}

export function SetMinFreeDiskPercent(arg1) {
  return window['go']['main']['App']['SetMinFreeDiskPercent'](arg1);
}

export function SetNotifications(arg1) {
  return window['go']['main']['App']['SetNotifications'](arg1);
}

export function SetReceivingEnabled(arg1) {
  return window['go']['main']['App']['SetReceivingEnabled'](arg1);
}

export function SetRejectedExtensions(arg1) {
  return window['go']['main']['App']['SetRejectedExtensions'](arg1);
}

export function SetTCPAcceptCooldownSeconds(arg1) {
  return window['go']['main']['App']['SetTCPAcceptCooldownSeconds'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['main']['App']['SetTheme'](arg1);
}

export function SetUDPHelloCooldownSeconds(arg1) {
  return window['go']['main']['App']['SetUDPHelloCooldownSeconds'](arg1);
}

export function SetWhitelistEnabled(arg1) {
  return window['go']['main']['App']['SetWhitelistEnabled'](arg1);
}

export function Signature() {
  return window['go']['main']['App']['Signature']();
}

export function StashPastedImage(arg1, arg2) {
  return window['go']['main']['App']['StashPastedImage'](arg1, arg2);
}

export function TCPAcceptCooldownSeconds() {
  return window['go']['main']['App']['TCPAcceptCooldownSeconds']();
}

export function Theme() {
  return window['go']['main']['App']['Theme']();
}

export function UDPHelloCooldownSeconds() {
  return window['go']['main']['App']['UDPHelloCooldownSeconds']();
}

export function UnblockPeer(arg1) {
  return window['go']['main']['App']['UnblockPeer'](arg1);
}

export function Whitelist() {
  return window['go']['main']['App']['Whitelist']();
}

export function WhitelistEnabled() {
  return window['go']['main']['App']['WhitelistEnabled']();
}
