// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audit} from '../models';
import {main} from '../models';
import {settings} from '../models';

export function AddManualPeer(arg1:string):Promise<void>;

export function AddWhitelist(arg1:string):Promise<void>;

export function Aliases():Promise<Record<string, string>>;

export function AllowedInterfaces():Promise<Array<string>>;

export function AuditEntries():Promise<Array<audit.Entry>>;

export function AvailableInterfaces():Promise<Array<main.InterfaceView>>;

export function BlockPeer(arg1:string):Promise<void>;

export function BlockedPeers():Promise<Array<string>>;

export function BuddyName():Promise<string>;

export function CancelPairing():Promise<void>;

export function CancelTransfer():Promise<void>;

export function ClearAudit():Promise<void>;

export function ClearCustomAvatar():Promise<void>;

export function ClearHistory():Promise<void>;

export function CloseToTray():Promise<boolean>;

export function ConfirmUnknownPeers():Promise<boolean>;

export function CopyToClipboard(arg1:string):Promise<void>;

export function DestDir():Promise<string>;

export function ExportHistory(arg1:string,arg2:string):Promise<string>;

export function FileHash(arg1:string):Promise<string>;

export function Fingerprint():Promise<string>;

export function ForgetApprovedPeers():Promise<void>;

export function HasCustomAvatar():Promise<boolean>;

export function History():Promise<Array<Record<string, any>>>;

export function IdleAutoDisableMinutes():Promise<number>;

export function IsPeerPinned(arg1:string):Promise<boolean>;

export function LargeFileThresholdMB():Promise<number>;

export function LocalAddresses():Promise<Array<string>>;

export function LocalAvatarDataURL():Promise<string>;

export function ManualPeers():Promise<Array<string>>;

export function MaxFilesPerSession():Promise<number>;

export function MaxPathDepth():Promise<number>;

export function MinFreeDiskPercent():Promise<number>;

export function Notifications():Promise<boolean>;

export function OpenPath(arg1:string):Promise<void>;

export function PairWithPassphrase(arg1:string,arg2:string):Promise<void>;

export function Peers():Promise<Array<main.PeerView>>;

export function PickAndSetCustomAvatar():Promise<string>;

export function PickDestDir():Promise<string>;

export function PickExportPath(arg1:string):Promise<string>;

export function PickFilesToSend():Promise<Array<string>>;

export function PickFolderToSend():Promise<string>;

export function PinPeer(arg1:string,arg2:string):Promise<settings.PinnedPeer>;

export function PinnedPeers():Promise<Array<settings.PinnedPeer>>;

export function QRCodeSignature():Promise<string>;

export function ReceivingEnabled():Promise<boolean>;

export function RejectedExtensions():Promise<Array<string>>;

export function RemoveManualPeer(arg1:string):Promise<void>;

export function RemoveWhitelist(arg1:string):Promise<void>;

export function ResolvePendingSession(arg1:string,arg2:boolean):Promise<void>;

export function RevealInFolder(arg1:string):Promise<void>;

export function SendClipboard(arg1:string):Promise<void>;

export function SendFiles(arg1:string,arg2:Array<string>):Promise<void>;

export function SendFilesMulti(arg1:Array<string>,arg2:Array<string>):Promise<void>;

export function SendText(arg1:string,arg2:string):Promise<void>;

export function SetAlias(arg1:string,arg2:string):Promise<void>;

export function SetAllowedInterfaces(arg1:Array<string>):Promise<void>;

export function SetBuddyName(arg1:string):Promise<void>;

export function SetCloseToTray(arg1:boolean):Promise<void>;

export function SetConfirmUnknownPeers(arg1:boolean):Promise<void>;

export function SetDestDir(arg1:string):Promise<void>;

export function SetIdleAutoDisableMinutes(arg1:number):Promise<void>;

export function SetLargeFileThresholdMB(arg1:number):Promise<void>;

export function SetMaxFilesPerSession(arg1:number):Promise<void>;

export function SetMaxPathDepth(arg1:number):Promise<void>;

export function SetMinFreeDiskPercent(arg1:number):Promise<void>;

export function SetNotifications(arg1:boolean):Promise<void>;

export function SetReceivingEnabled(arg1:boolean):Promise<void>;

export function SetRejectedExtensions(arg1:Array<string>):Promise<void>;

export function SetTCPAcceptCooldownSeconds(arg1:number):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function SetUDPHelloCooldownSeconds(arg1:number):Promise<void>;

export function SetWhitelistEnabled(arg1:boolean):Promise<void>;

export function Signature():Promise<string>;

export function StartPairing():Promise<string>;

export function StashPastedImage(arg1:string,arg2:string):Promise<string>;

export function TCPAcceptCooldownSeconds():Promise<number>;

export function Theme():Promise<string>;

export function UDPHelloCooldownSeconds():Promise<number>;

export function UnblockPeer(arg1:string):Promise<void>;

export function UnpinPeer(arg1:string):Promise<void>;

export function Whitelist():Promise<Array<string>>;

export function WhitelistEnabled():Promise<boolean>;
